# Generated by Django 5.2.4 on 2025-08-22 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_nickname'),
        ('bookinfo', '0003_bookinfolibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preference_keyword', models.JSONField(blank=True, null=True)),
                ('preference_vector', models.JSONField(blank=True, null=True)),
                ('preference_vector_survey', models.JSONField(blank=True, null=True)),
                ('preference_vector_activity', models.JSONField(blank=True, null=True)),
                ('survey_done', models.BooleanField(default=False)),
                ('last_survey_at', models.DateTimeField(blank=True, null=True)),
                ('points', models.BigIntegerField(default=0)),
                ('my_lib_ids', models.JSONField(blank=True, default=list)),
                ('preference_book', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DONATED', '기증'), ('PURCHASED', '구매')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quantity', models.IntegerField(default=0)),
                ('bookinfo', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.PROTECT, related_name='userbook_links', related_query_name='userbook', to='bookinfo.bookinfo')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='users_userb_user_id_4d5199_idx'), models.Index(fields=['bookinfo', 'created_at'], name='users_userb_isbn_14d16a_idx')],
                'unique_together': {('user', 'bookinfo')},
            },
        ),
    ]
