# Generated by Django 5.2.4 on 2025-08-22 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_bookinfolibrary'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userbook',
            name='users_userb_isbn_14d16a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'bookinfo', 'status')},
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['bookinfo', 'status', 'created_at'], name='users_userb_isbn_b33b6a_idx'),
        ),
    ]
