# Generated by Django 5.2.4 on 2025-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userbook_users_userb_isbn_14d16a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='library_id',
            field=models.IntegerField(null=True),
        ),
    ]
