# Generated by Django 5.2.4 on 2025-08-22 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_bookinfolibrary'),
        ('users', '0003_userbook_library_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userbook',
            name='users_userb_user_id_4d5199_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbook',
            name='users_userb_isbn_b33b6a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'status'], name='users_userb_user_id_577e63_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['bookinfo', 'status'], name='users_userb_isbn_578b10_idx'),
        ),
    ]
