# Generated by Django 5.2.4 on 2025-08-13 03:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0003_alter_userbook_book_alter_userbook_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['user', 'status', 'created_at'], name='users_userb_user_id_4d5199_idx'),
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['book', 'created_at'], name='users_userb_book_id_06ec36_idx'),
        ),
    ]
