# Generated by Django 5.2.4 on 2025-08-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
