# Generated by Django 5.2.4 on 2025-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userbook_users_userb_user_id_4d5199_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='preference_book',
            new_name='preference_book_activity',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preference_book_combined',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
