# Generated by Django 5.2.5 on 2025-08-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_preference_book_userinfo_preference_book_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
