# Generated by Django 5.2.4 on 2025-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userbook_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_survey_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='survey_done',
            field=models.BooleanField(default=False),
        ),
    ]
