# Generated by Django 5.2.4 on 2025-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userinfo_last_survey_at_userinfo_survey_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='my_lib',
            field=models.BigIntegerField(default=0),
        ),
    ]
