# Generated by Django 5.2.4 on 2025-08-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinfo_my_lib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='my_lib',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='my_lib_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
