# Generated by Django 5.2.4 on 2025-08-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userinfo_my_lib_userinfo_my_lib_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='preference_vector_activity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preference_vector_survey',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
