# Generated by Django 5.2.4 on 2025-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userinfo_preference_vector_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preference_book',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
