# Generated by Django 5.2.4 on 2025-08-11 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookinfo', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('regular_price', models.IntegerField(blank=True, null=True)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', '구매가능'), ('PICKED', '구매불가'), ('EXPIRED', '만료')], default='AVAILABLE', max_length=20)),
                ('donor_user', models.ForeignKey(blank=True, db_column='donor_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_books', to=settings.AUTH_USER_MODEL)),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bookinfo.bookinfo')),
                ('library', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library.library')),
            ],
            options={
                'db_table': 'Book',
                'indexes': [models.Index(fields=['library', 'status'], name='Book_library_b21948_idx'), models.Index(fields=['library', 'isbn', 'status'], name='Book_library_0e4662_idx')],
            },
        ),
    ]
