# Generated by Django 5.2.4 on 2025-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', '구매가능'), ('PICKED', '구매불가'), ('EXPIRED', '만료'), ('REVERVATIONED', '예약')], default='AVAILABLE', max_length=20),
        ),
    ]
