# Generated by Django 5.2.4 on 2025-08-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
