# Generated by Django 5.2.4 on 2025-08-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_survey',
            field=models.BooleanField(default=False),
        ),
    ]
