# Generated by Django 5.2.4 on 2025-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='저자')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='출판사')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='출간일')),
                ('cover_url', models.URLField(blank=True, max_length=500, verbose_name='표지 이미지')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='카테고리')),
                ('regular_price', models.IntegerField(blank=True, null=True, verbose_name='정가')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('vector', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '책 메타',
                'verbose_name_plural': '책 메타',
                'db_table': 'BookInfo',
                'indexes': [models.Index(fields=['title'], name='BookInfo_title_1e0313_idx'), models.Index(fields=['author'], name='BookInfo_author_1e9323_idx'), models.Index(fields=['publisher'], name='BookInfo_publish_e46d50_idx'), models.Index(fields=['category'], name='BookInfo_categor_83447b_idx')],
            },
        ),
    ]
