# Generated by Django 5.2.4 on 2025-08-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='정가'),
        ),
    ]
