# Generated by Django 5.2.4 on 2025-08-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0002_bookinfo_sale_price'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', '구매가능'), ('PICKED', '구매불가'), ('EXPIRED', '만료')], default='AVAILABLE', max_length=20)),
                ('median_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.CASCADE, related_name='bookinfo', to='bookinfo.bookinfo')),
                ('library_id', models.ForeignKey(db_column='library_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookinfo', to='library.library')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('library_id', 'isbn'), name='uniq_library_isbn_bil')],
            },
        ),
    ]
